[default]
SECRET_KEY = 'abc'
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = ['app.extensions:init_app']

[development]
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.sqlite'

[testing]
WTF_CSRF_ENABLED = false
SQLALCHEMY_DATABASE_URI = 'sqlite:///'