[default]
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = ['app.routes:init_app', 'app.extensions:init_app']

[development]
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.sqlite'

[testing]
WTF_CSRF_ENABLED = false
SECRET_KEY = 'abc'
SQLALCHEMY_DATABASE_URI = 'sqlite:///'